name: flutter_redux_provider_pattern
description: An application of Redux architecture with Provider package.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2


  # for Redux
  redux: ^3.0.0
  redux_types: ^0.2.0

  # for Provider
  provider: ^3.2.0
  subscription_holder: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.4.0
flutter:
  uses-material-design: true

